### ISSUE TITLE
B.Fave  and hydrosideLookup.m

### ISSUE THREAD

**Issue by minggo2023** [JoeyGraz11/vpp#1]
Thanks for your code, it helps me a lot about understanding vpp. I have some questions about your code.
what is `B.Fave` ?  how do you get `sailArm = S.CEt - (B.Tc + B.Fave - B.VCG)`?  reference? I cannot find it in the PYD 2022.
and I also cannnot  find the formula `Ch = b1*(D^2/Sc) + b2*(D^2/Sc)^2 + b3*(Tc/D) + b4*(Tc/D)*(D^2/Sc)` in `hydrosideLookup.m`. can you give me reference.
PS: Forgive my poor english

**Comment by jgrazian** [comment]
Hi,

I am glad you are finding the code useful. I apologize for it's messiness.

For reference I used the 3rd edition of PYD (2007) to implement this code.

I am not entirely sure what `B.Fave` is. My best guess is that it stands for `Average Freeboard` as the sailArm equation seems to be solving for a vertical height at which to apply sail force. Again, I am not entirely sure about this.

As referenced in the comment near the `Ch` equation that code came from PYD Figure 6.12. Hydrodynamic Side Force. I will try to attach an image of the relevant figure.

**Comment by jgrazian** [comment]
![image](https://user-images.githubusercontent.com/34037413/236707152-177beba5-19b2-4ae9-90fa-7c72b89432f9.jpeg)

**Comment by minggo2023** [comment]
Thank you for taking the time to reply. Your answer has helped me a lot. Thank you again for your sharing and I wish you a happy life
